### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by xigrug** [a4m/get-packtpub-free-ebook#1]
Free Book for Toady:Mastering Wireshark
Traceback (most recent call last):
  File "get_free_ebook_from_packtpub.py", line 78, in <module>
    main()
  File "get_free_ebook_from_packtpub.py", line 74, in main
    free_link = step3()
  File "get_free_ebook_from_packtpub.py", line 50, in step3
    link = soup.find_all('a',attrs={'class':'twelve-days-claim'})[0]
IndexError: list index out of range

**Comment by a4m** [comment]
i will try to fix it later

**Comment by a4m** [comment]
我看了下，`list index out of range`这个错误已经解决了，但是**目前我的这个脚本已经不能自动领取免费电子书了**。

遇到的最关键的问题是**在发送领取电子书的post包时，遇到了谷歌的reCAPTCHA验证码**。

但是我不知道怎么破解这种验证码，这个项目也就不了了之了。
